/**
 * generated by Xtext 2.12.0
 */
package org.xtext.watercraftHQ.water.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.XtextRunner;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.xtext.watercraftHQ.water.tests.WaterInjectorProvider;

@RunWith(XtextRunner.class)
@InjectWith(WaterInjectorProvider.class)
@SuppressWarnings("all")
public class WaterParsingTest {
  @Inject
  private /* ParseHelper<Model> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field WaterParsingTest.parseHelper refers to the missing type Model"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved");
  }
}
