/*
 * generated by Xtext 2.12.0
 */
package org.xtext.watercraftHQ.water.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.watercraftHQ.water.ui.internal.WaterActivator;

public class WaterUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return WaterActivator.getInstance().getInjector("org.xtext.watercraftHQ.water.Water");
	}

}
