/*
 * generated by Xtext 2.12.0
 */
package org.xtext.watercraftHQ.water.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.watercraftHQ.water.ui.internal.WaterActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class WaterExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return WaterActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return WaterActivator.getInstance().getInjector(WaterActivator.ORG_XTEXT_WATERCRAFTHQ_WATER_WATER);
	}
	
}
