/**
 * generated by Xtext 2.12.0
 */
package org.xtext.watercraftHQ.water.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.watercraftHQ.water.ui.AbstractWaterUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class WaterUiModule extends AbstractWaterUiModule {
  public WaterUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
