/**
 * generated by Xtext 2.12.0
 */
package org.xtext.watercraftHQ.water.ui.contentassist;

import org.xtext.watercraftHQ.water.ui.contentassist.AbstractWaterProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class WaterProposalProvider extends AbstractWaterProposalProvider {
}
