/**
 * generated by Xtext 2.12.0
 */
package org.xtext.watercraftHQ.water.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.watercraftHQ.water.WaterRuntimeModule;
import org.xtext.watercraftHQ.water.WaterStandaloneSetup;
import org.xtext.watercraftHQ.water.ide.WaterIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class WaterIdeSetup extends WaterStandaloneSetup {
  @Override
  public Injector createInjector() {
    WaterRuntimeModule _waterRuntimeModule = new WaterRuntimeModule();
    WaterIdeModule _waterIdeModule = new WaterIdeModule();
    return Guice.createInjector(Modules2.mixin(_waterRuntimeModule, _waterIdeModule));
  }
}
