/**
 * generated by Xtext 2.12.0
 */
package org.xtext.watercraftHQ.water.ide;

import org.xtext.watercraftHQ.water.ide.AbstractWaterIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class WaterIdeModule extends AbstractWaterIdeModule {
}
