grammar org.xtext.watercraftHQ.water.Water with org.eclipse.xtext.common.Terminals

generate water "http://www.xtext.org/watercraftHQ/water/Water"

Domainmodel :
    (elements+=Type)*;
  
Type:
    DataType | Entity;
  
DataType:
    'datatype' name=ID;
 
Entity:
    'entity' name=ID ('extends' superType=[Entity])? '{'
        (features+=Feature)*
    '}';
 
Feature:
    (many?='many')? name=ID ':' type=[Type];