/*
 * generated by Xtext 2.12.0
 */
package org.xtext.watercraftHQ.water


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class WaterRuntimeModule extends AbstractWaterRuntimeModule {
}
