/*
 * generated by Xtext 2.12.0
 */
package org.xtext.watercraftHQ.water


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class WaterStandaloneSetup extends WaterStandaloneSetupGenerated {

	def static void doSetup() {
		new WaterStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
