/**
 * generated by Xtext 2.12.0
 */
package org.xtext.watercraftHQ.water.water;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.watercraftHQ.water.water.WaterPackage#getDataType()
 * @model
 * @generated
 */
public interface DataType extends Type
{
} // DataType
