/**
 * generated by Xtext 2.12.0
 */
package org.xtext.watercraftHQ.water.water;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Hero</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.watercraftHQ.water.water.Hero#getPosition <em>Position</em>}</li>
 *   <li>{@link org.xtext.watercraftHQ.water.water.Hero#isIsBoss <em>Is Boss</em>}</li>
 * </ul>
 *
 * @see org.xtext.watercraftHQ.water.water.WaterPackage#getHero()
 * @model
 * @generated
 */
public interface Hero extends Type
{
  /**
   * Returns the value of the '<em><b>Position</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Position</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Position</em>' containment reference.
   * @see #setPosition(Position)
   * @see org.xtext.watercraftHQ.water.water.WaterPackage#getHero_Position()
   * @model containment="true"
   * @generated
   */
  Position getPosition();

  /**
   * Sets the value of the '{@link org.xtext.watercraftHQ.water.water.Hero#getPosition <em>Position</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Position</em>' containment reference.
   * @see #getPosition()
   * @generated
   */
  void setPosition(Position value);

  /**
   * Returns the value of the '<em><b>Is Boss</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Is Boss</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Boss</em>' attribute.
   * @see #setIsBoss(boolean)
   * @see org.xtext.watercraftHQ.water.water.WaterPackage#getHero_IsBoss()
   * @model
   * @generated
   */
  boolean isIsBoss();

  /**
   * Sets the value of the '{@link org.xtext.watercraftHQ.water.water.Hero#isIsBoss <em>Is Boss</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Boss</em>' attribute.
   * @see #isIsBoss()
   * @generated
   */
  void setIsBoss(boolean value);

} // Hero
