/**
 * generated by Xtext 2.12.0
 */
package org.xtext.watercraftHQ.water.water;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.watercraftHQ.water.water.WaterPackage#getType()
 * @model
 * @generated
 */
public interface Type extends EObject
{
} // Type
