/**
 * generated by Xtext 2.12.0
 */
package org.xtext.watercraftHQ.water.water;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.watercraftHQ.water.water.WaterFactory
 * @model kind="package"
 * @generated
 */
public interface WaterPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "water";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/watercraftHQ/water/Water";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "water";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  WaterPackage eINSTANCE = org.xtext.watercraftHQ.water.water.impl.WaterPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.watercraftHQ.water.water.impl.ComputerGameImpl <em>Computer Game</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.watercraftHQ.water.water.impl.ComputerGameImpl
   * @see org.xtext.watercraftHQ.water.water.impl.WaterPackageImpl#getComputerGame()
   * @generated
   */
  int COMPUTER_GAME = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPUTER_GAME__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Computer Game</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPUTER_GAME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.watercraftHQ.water.water.impl.TypeImpl <em>Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.watercraftHQ.water.water.impl.TypeImpl
   * @see org.xtext.watercraftHQ.water.water.impl.WaterPackageImpl#getType()
   * @generated
   */
  int TYPE = 1;

  /**
   * The number of structural features of the '<em>Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.watercraftHQ.water.water.impl.LevelImpl <em>Level</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.watercraftHQ.water.water.impl.LevelImpl
   * @see org.xtext.watercraftHQ.water.water.impl.WaterPackageImpl#getLevel()
   * @generated
   */
  int LEVEL = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEVEL__NAME = TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Field</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEVEL__FIELD = TYPE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Level</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LEVEL_FEATURE_COUNT = TYPE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.watercraftHQ.water.water.impl.FieldImpl <em>Field</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.watercraftHQ.water.water.impl.FieldImpl
   * @see org.xtext.watercraftHQ.water.water.impl.WaterPackageImpl#getField()
   * @generated
   */
  int FIELD = 3;

  /**
   * The feature id for the '<em><b>Rectangle</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__RECTANGLE = 0;

  /**
   * The feature id for the '<em><b>Heros</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__HEROS = 1;

  /**
   * The feature id for the '<em><b>Items</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD__ITEMS = 2;

  /**
   * The number of structural features of the '<em>Field</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIELD_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.watercraftHQ.water.water.impl.RectangleImpl <em>Rectangle</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.watercraftHQ.water.water.impl.RectangleImpl
   * @see org.xtext.watercraftHQ.water.water.impl.WaterPackageImpl#getRectangle()
   * @generated
   */
  int RECTANGLE = 4;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECTANGLE__X = 0;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECTANGLE__Y = 1;

  /**
   * The number of structural features of the '<em>Rectangle</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RECTANGLE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.watercraftHQ.water.water.impl.HeroImpl <em>Hero</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.watercraftHQ.water.water.impl.HeroImpl
   * @see org.xtext.watercraftHQ.water.water.impl.WaterPackageImpl#getHero()
   * @generated
   */
  int HERO = 5;

  /**
   * The feature id for the '<em><b>Position</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HERO__POSITION = TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Is Boss</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HERO__IS_BOSS = TYPE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Hero</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HERO_FEATURE_COUNT = TYPE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.watercraftHQ.water.water.impl.PositionImpl <em>Position</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.watercraftHQ.water.water.impl.PositionImpl
   * @see org.xtext.watercraftHQ.water.water.impl.WaterPackageImpl#getPosition()
   * @generated
   */
  int POSITION = 6;

  /**
   * The feature id for the '<em><b>X</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POSITION__X = 0;

  /**
   * The feature id for the '<em><b>Y</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POSITION__Y = 1;

  /**
   * The number of structural features of the '<em>Position</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POSITION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.watercraftHQ.water.water.impl.ItemImpl <em>Item</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.watercraftHQ.water.water.impl.ItemImpl
   * @see org.xtext.watercraftHQ.water.water.impl.WaterPackageImpl#getItem()
   * @generated
   */
  int ITEM = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM__NAME = TYPE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Attack Bonus</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM__ATTACK_BONUS = TYPE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Defense Bonus</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM__DEFENSE_BONUS = TYPE_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Location</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM__LOCATION = TYPE_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Hero</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM__HERO = TYPE_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Item</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ITEM_FEATURE_COUNT = TYPE_FEATURE_COUNT + 5;


  /**
   * Returns the meta object for class '{@link org.xtext.watercraftHQ.water.water.ComputerGame <em>Computer Game</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Computer Game</em>'.
   * @see org.xtext.watercraftHQ.water.water.ComputerGame
   * @generated
   */
  EClass getComputerGame();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.watercraftHQ.water.water.ComputerGame#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.watercraftHQ.water.water.ComputerGame#getElements()
   * @see #getComputerGame()
   * @generated
   */
  EReference getComputerGame_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.watercraftHQ.water.water.Type <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Type</em>'.
   * @see org.xtext.watercraftHQ.water.water.Type
   * @generated
   */
  EClass getType();

  /**
   * Returns the meta object for class '{@link org.xtext.watercraftHQ.water.water.Level <em>Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Level</em>'.
   * @see org.xtext.watercraftHQ.water.water.Level
   * @generated
   */
  EClass getLevel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.watercraftHQ.water.water.Level#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.watercraftHQ.water.water.Level#getName()
   * @see #getLevel()
   * @generated
   */
  EAttribute getLevel_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.watercraftHQ.water.water.Level#getField <em>Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Field</em>'.
   * @see org.xtext.watercraftHQ.water.water.Level#getField()
   * @see #getLevel()
   * @generated
   */
  EReference getLevel_Field();

  /**
   * Returns the meta object for class '{@link org.xtext.watercraftHQ.water.water.Field <em>Field</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Field</em>'.
   * @see org.xtext.watercraftHQ.water.water.Field
   * @generated
   */
  EClass getField();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.watercraftHQ.water.water.Field#getRectangle <em>Rectangle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rectangle</em>'.
   * @see org.xtext.watercraftHQ.water.water.Field#getRectangle()
   * @see #getField()
   * @generated
   */
  EReference getField_Rectangle();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.watercraftHQ.water.water.Field#getHeros <em>Heros</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Heros</em>'.
   * @see org.xtext.watercraftHQ.water.water.Field#getHeros()
   * @see #getField()
   * @generated
   */
  EReference getField_Heros();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.watercraftHQ.water.water.Field#getItems <em>Items</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Items</em>'.
   * @see org.xtext.watercraftHQ.water.water.Field#getItems()
   * @see #getField()
   * @generated
   */
  EReference getField_Items();

  /**
   * Returns the meta object for class '{@link org.xtext.watercraftHQ.water.water.Rectangle <em>Rectangle</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rectangle</em>'.
   * @see org.xtext.watercraftHQ.water.water.Rectangle
   * @generated
   */
  EClass getRectangle();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.watercraftHQ.water.water.Rectangle#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see org.xtext.watercraftHQ.water.water.Rectangle#getX()
   * @see #getRectangle()
   * @generated
   */
  EAttribute getRectangle_X();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.watercraftHQ.water.water.Rectangle#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see org.xtext.watercraftHQ.water.water.Rectangle#getY()
   * @see #getRectangle()
   * @generated
   */
  EAttribute getRectangle_Y();

  /**
   * Returns the meta object for class '{@link org.xtext.watercraftHQ.water.water.Hero <em>Hero</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Hero</em>'.
   * @see org.xtext.watercraftHQ.water.water.Hero
   * @generated
   */
  EClass getHero();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.watercraftHQ.water.water.Hero#getPosition <em>Position</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Position</em>'.
   * @see org.xtext.watercraftHQ.water.water.Hero#getPosition()
   * @see #getHero()
   * @generated
   */
  EReference getHero_Position();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.watercraftHQ.water.water.Hero#isIsBoss <em>Is Boss</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Is Boss</em>'.
   * @see org.xtext.watercraftHQ.water.water.Hero#isIsBoss()
   * @see #getHero()
   * @generated
   */
  EAttribute getHero_IsBoss();

  /**
   * Returns the meta object for class '{@link org.xtext.watercraftHQ.water.water.Position <em>Position</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Position</em>'.
   * @see org.xtext.watercraftHQ.water.water.Position
   * @generated
   */
  EClass getPosition();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.watercraftHQ.water.water.Position#getX <em>X</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X</em>'.
   * @see org.xtext.watercraftHQ.water.water.Position#getX()
   * @see #getPosition()
   * @generated
   */
  EAttribute getPosition_X();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.watercraftHQ.water.water.Position#getY <em>Y</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Y</em>'.
   * @see org.xtext.watercraftHQ.water.water.Position#getY()
   * @see #getPosition()
   * @generated
   */
  EAttribute getPosition_Y();

  /**
   * Returns the meta object for class '{@link org.xtext.watercraftHQ.water.water.Item <em>Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Item</em>'.
   * @see org.xtext.watercraftHQ.water.water.Item
   * @generated
   */
  EClass getItem();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.watercraftHQ.water.water.Item#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.watercraftHQ.water.water.Item#getName()
   * @see #getItem()
   * @generated
   */
  EAttribute getItem_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.watercraftHQ.water.water.Item#getAttackBonus <em>Attack Bonus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Attack Bonus</em>'.
   * @see org.xtext.watercraftHQ.water.water.Item#getAttackBonus()
   * @see #getItem()
   * @generated
   */
  EAttribute getItem_AttackBonus();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.watercraftHQ.water.water.Item#getDefenseBonus <em>Defense Bonus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Defense Bonus</em>'.
   * @see org.xtext.watercraftHQ.water.water.Item#getDefenseBonus()
   * @see #getItem()
   * @generated
   */
  EAttribute getItem_DefenseBonus();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.watercraftHQ.water.water.Item#getLocation <em>Location</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Location</em>'.
   * @see org.xtext.watercraftHQ.water.water.Item#getLocation()
   * @see #getItem()
   * @generated
   */
  EReference getItem_Location();

  /**
   * Returns the meta object for the reference '{@link org.xtext.watercraftHQ.water.water.Item#getHero <em>Hero</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Hero</em>'.
   * @see org.xtext.watercraftHQ.water.water.Item#getHero()
   * @see #getItem()
   * @generated
   */
  EReference getItem_Hero();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  WaterFactory getWaterFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.watercraftHQ.water.water.impl.ComputerGameImpl <em>Computer Game</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.watercraftHQ.water.water.impl.ComputerGameImpl
     * @see org.xtext.watercraftHQ.water.water.impl.WaterPackageImpl#getComputerGame()
     * @generated
     */
    EClass COMPUTER_GAME = eINSTANCE.getComputerGame();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPUTER_GAME__ELEMENTS = eINSTANCE.getComputerGame_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.watercraftHQ.water.water.impl.TypeImpl <em>Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.watercraftHQ.water.water.impl.TypeImpl
     * @see org.xtext.watercraftHQ.water.water.impl.WaterPackageImpl#getType()
     * @generated
     */
    EClass TYPE = eINSTANCE.getType();

    /**
     * The meta object literal for the '{@link org.xtext.watercraftHQ.water.water.impl.LevelImpl <em>Level</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.watercraftHQ.water.water.impl.LevelImpl
     * @see org.xtext.watercraftHQ.water.water.impl.WaterPackageImpl#getLevel()
     * @generated
     */
    EClass LEVEL = eINSTANCE.getLevel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LEVEL__NAME = eINSTANCE.getLevel_Name();

    /**
     * The meta object literal for the '<em><b>Field</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LEVEL__FIELD = eINSTANCE.getLevel_Field();

    /**
     * The meta object literal for the '{@link org.xtext.watercraftHQ.water.water.impl.FieldImpl <em>Field</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.watercraftHQ.water.water.impl.FieldImpl
     * @see org.xtext.watercraftHQ.water.water.impl.WaterPackageImpl#getField()
     * @generated
     */
    EClass FIELD = eINSTANCE.getField();

    /**
     * The meta object literal for the '<em><b>Rectangle</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIELD__RECTANGLE = eINSTANCE.getField_Rectangle();

    /**
     * The meta object literal for the '<em><b>Heros</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIELD__HEROS = eINSTANCE.getField_Heros();

    /**
     * The meta object literal for the '<em><b>Items</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIELD__ITEMS = eINSTANCE.getField_Items();

    /**
     * The meta object literal for the '{@link org.xtext.watercraftHQ.water.water.impl.RectangleImpl <em>Rectangle</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.watercraftHQ.water.water.impl.RectangleImpl
     * @see org.xtext.watercraftHQ.water.water.impl.WaterPackageImpl#getRectangle()
     * @generated
     */
    EClass RECTANGLE = eINSTANCE.getRectangle();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECTANGLE__X = eINSTANCE.getRectangle_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RECTANGLE__Y = eINSTANCE.getRectangle_Y();

    /**
     * The meta object literal for the '{@link org.xtext.watercraftHQ.water.water.impl.HeroImpl <em>Hero</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.watercraftHQ.water.water.impl.HeroImpl
     * @see org.xtext.watercraftHQ.water.water.impl.WaterPackageImpl#getHero()
     * @generated
     */
    EClass HERO = eINSTANCE.getHero();

    /**
     * The meta object literal for the '<em><b>Position</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HERO__POSITION = eINSTANCE.getHero_Position();

    /**
     * The meta object literal for the '<em><b>Is Boss</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HERO__IS_BOSS = eINSTANCE.getHero_IsBoss();

    /**
     * The meta object literal for the '{@link org.xtext.watercraftHQ.water.water.impl.PositionImpl <em>Position</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.watercraftHQ.water.water.impl.PositionImpl
     * @see org.xtext.watercraftHQ.water.water.impl.WaterPackageImpl#getPosition()
     * @generated
     */
    EClass POSITION = eINSTANCE.getPosition();

    /**
     * The meta object literal for the '<em><b>X</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute POSITION__X = eINSTANCE.getPosition_X();

    /**
     * The meta object literal for the '<em><b>Y</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute POSITION__Y = eINSTANCE.getPosition_Y();

    /**
     * The meta object literal for the '{@link org.xtext.watercraftHQ.water.water.impl.ItemImpl <em>Item</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.watercraftHQ.water.water.impl.ItemImpl
     * @see org.xtext.watercraftHQ.water.water.impl.WaterPackageImpl#getItem()
     * @generated
     */
    EClass ITEM = eINSTANCE.getItem();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ITEM__NAME = eINSTANCE.getItem_Name();

    /**
     * The meta object literal for the '<em><b>Attack Bonus</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ITEM__ATTACK_BONUS = eINSTANCE.getItem_AttackBonus();

    /**
     * The meta object literal for the '<em><b>Defense Bonus</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ITEM__DEFENSE_BONUS = eINSTANCE.getItem_DefenseBonus();

    /**
     * The meta object literal for the '<em><b>Location</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ITEM__LOCATION = eINSTANCE.getItem_Location();

    /**
     * The meta object literal for the '<em><b>Hero</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ITEM__HERO = eINSTANCE.getItem_Hero();

  }

} //WaterPackage
