/**
 * generated by Xtext 2.12.0
 */
package org.xtext.watercraftHQ.water.water;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.watercraftHQ.water.water.WaterFactory
 * @model kind="package"
 * @generated
 */
public interface WaterPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "water";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/watercraftHQ/water/Water";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "water";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  WaterPackage eINSTANCE = org.xtext.watercraftHQ.water.water.impl.WaterPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.watercraftHQ.water.water.impl.DomainmodelImpl <em>Domainmodel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.watercraftHQ.water.water.impl.DomainmodelImpl
   * @see org.xtext.watercraftHQ.water.water.impl.WaterPackageImpl#getDomainmodel()
   * @generated
   */
  int DOMAINMODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAINMODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Domainmodel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOMAINMODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.watercraftHQ.water.water.impl.ComponentImpl <em>Component</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.watercraftHQ.water.water.impl.ComponentImpl
   * @see org.xtext.watercraftHQ.water.water.impl.WaterPackageImpl#getComponent()
   * @generated
   */
  int COMPONENT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Component</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.watercraftHQ.water.water.impl.WaterClassImpl <em>Class</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.watercraftHQ.water.water.impl.WaterClassImpl
   * @see org.xtext.watercraftHQ.water.water.impl.WaterPackageImpl#getWaterClass()
   * @generated
   */
  int WATER_CLASS = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WATER_CLASS__NAME = COMPONENT__NAME;

  /**
   * The feature id for the '<em><b>Variables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WATER_CLASS__VARIABLES = COMPONENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Class</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WATER_CLASS_FEATURE_COUNT = COMPONENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.watercraftHQ.water.water.impl.WaterVariablesImpl <em>Variables</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.watercraftHQ.water.water.impl.WaterVariablesImpl
   * @see org.xtext.watercraftHQ.water.water.impl.WaterPackageImpl#getWaterVariables()
   * @generated
   */
  int WATER_VARIABLES = 3;

  /**
   * The feature id for the '<em><b>Water Variables</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WATER_VARIABLES__WATER_VARIABLES = 0;

  /**
   * The number of structural features of the '<em>Variables</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WATER_VARIABLES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.watercraftHQ.water.water.impl.WaterVariableImpl <em>Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.watercraftHQ.water.water.impl.WaterVariableImpl
   * @see org.xtext.watercraftHQ.water.water.impl.WaterPackageImpl#getWaterVariable()
   * @generated
   */
  int WATER_VARIABLE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WATER_VARIABLE__NAME = COMPONENT__NAME;

  /**
   * The number of structural features of the '<em>Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WATER_VARIABLE_FEATURE_COUNT = COMPONENT_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link org.xtext.watercraftHQ.water.water.Domainmodel <em>Domainmodel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Domainmodel</em>'.
   * @see org.xtext.watercraftHQ.water.water.Domainmodel
   * @generated
   */
  EClass getDomainmodel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.watercraftHQ.water.water.Domainmodel#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see org.xtext.watercraftHQ.water.water.Domainmodel#getElements()
   * @see #getDomainmodel()
   * @generated
   */
  EReference getDomainmodel_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.watercraftHQ.water.water.Component <em>Component</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Component</em>'.
   * @see org.xtext.watercraftHQ.water.water.Component
   * @generated
   */
  EClass getComponent();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.watercraftHQ.water.water.Component#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.watercraftHQ.water.water.Component#getName()
   * @see #getComponent()
   * @generated
   */
  EAttribute getComponent_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.watercraftHQ.water.water.WaterClass <em>Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Class</em>'.
   * @see org.xtext.watercraftHQ.water.water.WaterClass
   * @generated
   */
  EClass getWaterClass();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.watercraftHQ.water.water.WaterClass#getVariables <em>Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Variables</em>'.
   * @see org.xtext.watercraftHQ.water.water.WaterClass#getVariables()
   * @see #getWaterClass()
   * @generated
   */
  EReference getWaterClass_Variables();

  /**
   * Returns the meta object for class '{@link org.xtext.watercraftHQ.water.water.WaterVariables <em>Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variables</em>'.
   * @see org.xtext.watercraftHQ.water.water.WaterVariables
   * @generated
   */
  EClass getWaterVariables();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.watercraftHQ.water.water.WaterVariables#getWaterVariables <em>Water Variables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Water Variables</em>'.
   * @see org.xtext.watercraftHQ.water.water.WaterVariables#getWaterVariables()
   * @see #getWaterVariables()
   * @generated
   */
  EReference getWaterVariables_WaterVariables();

  /**
   * Returns the meta object for class '{@link org.xtext.watercraftHQ.water.water.WaterVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable</em>'.
   * @see org.xtext.watercraftHQ.water.water.WaterVariable
   * @generated
   */
  EClass getWaterVariable();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  WaterFactory getWaterFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.watercraftHQ.water.water.impl.DomainmodelImpl <em>Domainmodel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.watercraftHQ.water.water.impl.DomainmodelImpl
     * @see org.xtext.watercraftHQ.water.water.impl.WaterPackageImpl#getDomainmodel()
     * @generated
     */
    EClass DOMAINMODEL = eINSTANCE.getDomainmodel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DOMAINMODEL__ELEMENTS = eINSTANCE.getDomainmodel_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.watercraftHQ.water.water.impl.ComponentImpl <em>Component</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.watercraftHQ.water.water.impl.ComponentImpl
     * @see org.xtext.watercraftHQ.water.water.impl.WaterPackageImpl#getComponent()
     * @generated
     */
    EClass COMPONENT = eINSTANCE.getComponent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENT__NAME = eINSTANCE.getComponent_Name();

    /**
     * The meta object literal for the '{@link org.xtext.watercraftHQ.water.water.impl.WaterClassImpl <em>Class</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.watercraftHQ.water.water.impl.WaterClassImpl
     * @see org.xtext.watercraftHQ.water.water.impl.WaterPackageImpl#getWaterClass()
     * @generated
     */
    EClass WATER_CLASS = eINSTANCE.getWaterClass();

    /**
     * The meta object literal for the '<em><b>Variables</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WATER_CLASS__VARIABLES = eINSTANCE.getWaterClass_Variables();

    /**
     * The meta object literal for the '{@link org.xtext.watercraftHQ.water.water.impl.WaterVariablesImpl <em>Variables</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.watercraftHQ.water.water.impl.WaterVariablesImpl
     * @see org.xtext.watercraftHQ.water.water.impl.WaterPackageImpl#getWaterVariables()
     * @generated
     */
    EClass WATER_VARIABLES = eINSTANCE.getWaterVariables();

    /**
     * The meta object literal for the '<em><b>Water Variables</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WATER_VARIABLES__WATER_VARIABLES = eINSTANCE.getWaterVariables_WaterVariables();

    /**
     * The meta object literal for the '{@link org.xtext.watercraftHQ.water.water.impl.WaterVariableImpl <em>Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.watercraftHQ.water.water.impl.WaterVariableImpl
     * @see org.xtext.watercraftHQ.water.water.impl.WaterPackageImpl#getWaterVariable()
     * @generated
     */
    EClass WATER_VARIABLE = eINSTANCE.getWaterVariable();

  }

} //WaterPackage
