/**
 * generated by Xtext 2.12.0
 */
package org.xtext.watercraftHQ.water.water;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.watercraftHQ.water.water.WaterPackage#getWaterVariable()
 * @model
 * @generated
 */
public interface WaterVariable extends Component
{
} // WaterVariable
