/*
 * generated by Xtext 2.12.0
 */
package org.xtext.watercraftHQ.water.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class WaterAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/watercraftHQ/water/parser/antlr/internal/InternalWater.tokens");
	}
}
