/*
 * generated by Xtext 2.12.0
 */
package org.xtext.watercraftHQ.water.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractWaterScopeProvider extends DelegatingScopeProvider {
}
